version: "3.10"
services:
  api:
    ports:
    - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_api
    env_file:
      - .env
    volumes:
      - api:/app
    depends_on:
      - redis
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  redis:
    image: redis
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "6379:6379"
#   ---
#   celery:
#    build:
#      dockerfile: Dockerfile.celery
#      context: .
#    volumes:
#      - api:/app
#    depends_on:
#      - api
#    ---
volumes:
  postgres_data:
  api:
